name: Java CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.4
      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Upload velocity plugin artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          # Artifact name
          name: AuthMeProxy-Velocity
          # A file, directory or wildcard pattern that describes what to upload
          path: velocity-plugin/target/velocity-plugin*.jar
      - name: Upload bungee plugin artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          # Artifact name
          name: AuthMeProxy-Bungee
          # A file, directory or wildcard pattern that describes what to upload
          path: bungee-plugin/target/bungee-plugin*.jar
      - name: Upload bukkit bridge artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          # Artifact name
          name: AuthMeVelocityBridge
          # A file, directory or wildcard pattern that describes what to upload
          path: bukkit-bridge/target/bukkit-bridge*.jar
      - name: Maven Dependency Tree Dependency Submission
        uses: advanced-security/maven-dependency-submission-action@v4.0.3
          
